config/routes.rb
Castly::Application.routes.draw do
  # resources :download_files

  resources :invite_inquiries#, :payments, :invites, :pages, :downloads, :videos, :users
  
  # resource :sessions
  root :to => "welcome#index"
  # 
  # get 'login' => "sessions#new"
  # get 'signup' => "users#new"
  # get 'logout' => "sessions#destroy"
end

app/models/download.rb
class Download < ActiveRecord::Base
  belongs_to :user
  has_many :download_files
  
  validates :user, :presence => true

  after_create :job_process

  has_attached_file :file  
  
  state_machine :initial => :created do
     after_transition :created => :downloading, :do => :notify_about_downloading
     after_transition :downloading => :transcoding, :do => :notify_about_downloading
     after_transition :transcoding => :finished, :do => :notify_about_downloading

     event :start do
       transition :created => :downloading
     end
     
     event :process do
       transition :created => :downloading, :downloading => :transcoding, :transcoding => :finished
    end

     state :created
     state :downloading
     state :transcoding
     state :finished
  end
  
  private
    def job_process
      job_type = torrent ? "TorrentDownload" : "FileDownload"
      Jobling::Processor.enqueue :processor => job_type, :args => id
    end
end

app/models/download_file.rb
class DownloadFile < ActiveRecord::Base
  belongs_to :download
end

app/models/invite.rb
class Invite < ActiveRecord::Base
end

app/models/invite_inquiry.rb
class InviteInquiry < ActiveRecord::Base
  validates :email, :presence => true, :uniqueness => true, :email => true
end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/payment.rb
class Payment < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic do |c|
    c.email_field :login
  end
  
  has_one  :invite, :class_name => "Invite", :foreign_key => "recipient_id"
  has_many :sent_invites, :class_name => "Invite", :foreign_key => "sender_id"
  
  has_many :downloads
  has_many :videos
  
  validates :invite_token, :presence => true
  
  def display_name
    super || login
  end
  
  def invite_token
    invite.token if invite
  end
  
  def invite_token=(v)
    self.invite = Invite.find_by_token(v)
  end
  
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  
end

app/models/video.rb
class Video < ActiveRecord::Base
end

app/models/video_file.rb
class VideoFile < ActiveRecord::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_item(path,title,klass = nil, counter = nil, additional_paths = [])
    additional_paths << path
    active_class =  "current" if additional_paths.map{|v| current_page?(v) }.include?(true)
    result = "<li class='nav-item #{klass} #{active_class}'>"
    common_body = content_tag(:span, title, :class => "text")
    common_body << simple_corners
    common_body << content_tag(:strong, counter, :class => "count") if counter
    result << if additional_paths.map{|v| current_page?(v) }.include?(true)
      common_body
     else
       link_to path do
         common_body
       end
     end
    result <<"</li>"
    raw result
  end
  
  def simple_corners
    '<i class="border-left"></i><i class="border-right"></i><i class="bg"></i>'.html_safe
  end
  
  def google_analytics
    "<script type='text/javascript'>

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-17912190-1']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    </script>".html_safe
  end
end

app/helpers/downloads_helper.rb
module DownloadsHelper
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" xml:lang="en">
  <head>
    <title>Castly</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="description" content="Castly" />
    <meta name="keywords" content="Castly" />
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    <meta name="apple-mobile-web-app-capable" content="yes" /> 
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=0" />
     <%= stylesheet_link_tag 'style' -%>
     <%= javascript_include_tag 'mc', 'application' -%>
     <%= google_analytics -%>
  </head>
  <body>
    <div class="background">
      <%= image_tag "bg.png", :width => "100%" %>
    </div>
    <div class="page">
      <%= render :partial => "shared/header" %>
      <%= render :partial => "shared/neck" %>
       <div class="body">
          <div class="container">
            <%= yield %>
          </div>
        </div>
      <%= render :partial => "shared/footer" %>
    </div>
  </body>
</html>

app/views/layouts/minimal.html.erb
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" xml:lang="en">
  <head>
    <title>Castly</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="description" content="Castly" />
    <meta name="keywords" content="Castly" />
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    <meta name="apple-mobile-web-app-capable" content="yes" /> 
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=0" />
    <%= stylesheet_link_tag 'prerelease' -%>
    <%= javascript_include_tag 'mc', 'application' -%>
    <%= google_analytics -%>
  </head>
  <body>
    <div class="page">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footerWrapper">
    <div class="left"><a href="#" class="bug">Found bug?</a></div>
    <div class="right"><a href="#" class="pp">Privacy Policy</a> <a href="#" class="useragreement">User Agreement</a></div>
  </div>
</div>

app/views/shared/_header.html.erb
<div class="header">
  <div class="header-wrapper">
    <div class="logo">
      <a href="/">
        <%= image_tag "logo.gif", :title => "Castly", :alt => "Castly" %>
      </a>
    </div>
    <div class="add-media">
      <a href="#">
        <span class="text">Add media</span>
        <i class="border-left"></i><i class="border-right"></i><i class="bg"></i>
      </a>
    </div>
    <div class="add-media-after-line"></div>
    <div class="invite-friends">
      <a href="#">
        <span class="text">Invite friends</span>
        <i class="border-left"></i><i class="border-right"></i><i class="bg"></i>
      </a>
    </div>
    <div class="header-right-panel">
      <div class="hero"></div>
      <div class="welcome-text">Welcome back, 
        <strong><%= current_user.display_name %>.</strong>
      </div>
      <ul class="nav">
        <li class="nav-item logout"><i></i>
          <%= link_to "Logout", logout_path %>
        </li>
        <li class="nav-item settings"><i></i>
          <%= link_to "Settings", "#" %>
        </li>
        <li class="nav-item help"><i></i>
          <%= link_to "Help", "#" %>
        </li>
      </ul>
      <div class="right-border"></div>
    </div>
  </div>
</div>

app/views/shared/_neck.html.erb
<div class="neck">
  <div class="nav-wrapper">
    <ul class="nav">
      <%= nav_item(videos_path,"Videos","videos") -%>
      <%= nav_item(root_path,"Store","store") -%>
      <%= nav_item(downloads_path,"Downloads","downloads",3) -%>
    </ul>
  </div>
  <div class="neck-search">
    <div class="wrapper">
      <input id="search" placeholder="Search" />
      <a href="#">
        <%= image_tag "neck-search-button.gif", :title => "Search", :alt => "Search" %>
      </a>
      <i class="border-left"></i><i class="border-right"></i><i class="bg"></i>
    </div>
  </div>
</div>
    